version: "3.9"

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "51214:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: databaseApp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
