services:
  server:
extends:
  file: docker-compose.common.yml
  services:
    server:
      command: sh -c "npx prisma generate && npx prisma migrate dev --name init && npm run dev" 
  database:
    image: postgres:15
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U postgres -d postgres"
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - database:/var/lib/postgresql/data
  proxy:
    image: caddy:2.7.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server
  cache:
      image: redis:7.2.4
      restart: unless-stopped
      command: redis-server --requirepass ${CACHE_PASSWORD}
      volumes:
        - cache:/data

volumes:
  database:
  caddy_data:
  caddy_config:
  cache: