services:
  server:
    extends:
      file: docker-compose.common.yml
      service: server
    ports:
      - '3000:3000'
    command: sh -c "npx prisma generate &&  npm run build && npm run start" 
    volumes:
      - .:/app  
      - /app/node_modules
  database:
    extends:
      file: docker-compose.common.yml
      service: database
    ports:
      - "5432:5432"
  proxy:
    extends:
      file: docker-compose.common.yml
      service: proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
  cache:
    extends:
      file: docker-compose.common.yml
      service: cache

volumes:
  database:
  caddy_data:
  caddy_config:
  cache: