services:
  server:
    restart: unless-stopped  
    build: .
    depends_on:
      database:
        condition: service_healthy
        restart: true
    environment:
      DATABASE_URL: "postgresql://postgres:${DATABASE_PASSWORD}@database:5432/postgres"
      CACHE_HOST: ${CACHE_HOST}
      CACHE_PORT: ${CACHE_PORT}
      CACHE_PASSWORD: ${CACHE_PASSWORD}
    ports:
      - '3000:3000'
    volumes:
      - .:/app  
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate dev --name init && npm run dev"
  database:
    image: postgres:15
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - database:/var/lib/postgresql/data
  proxy:
    image: caddy:2.7.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server
  cache:
      image: redis:7.2.4
      restart: unless-stopped
      command: redis-server --requirepass ${CACHE_PASSWORD}
      volumes:
        - cache:/data

volumes:
  database:
  caddy_data:
  caddy_config:
  cache: