services:
  server:
    restart: unless-stopped  
    build: .
    healthcheck:
          test: ["CMD-SHELL", "curl --fail http://localhost:3000/ || exit 1"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 10s
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_started
    environment:
      DATABASE_URL: "postgresql://postgres:${DATABASE_PASSWORD}@database:5432/postgres"
      CACHE_HOST: ${CACHE_HOST}
      CACHE_PORT: ${CACHE_PORT}
      CACHE_PASSWORD: ${CACHE_PASSWORD}

  database:
    image: postgres:15
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - database:/var/lib/postgresql/data
  proxy:
    image: caddy:2.7.4
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server
  cache:
      image: redis:7.2.4
      restart: unless-stopped
      healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 5s
        timeout: 5s
        retries: 5
        start_period: 5s
      command: redis-server --requirepass ${CACHE_PASSWORD}
      volumes:
        - cache:/data

volumes:
  database:
  caddy_data:
  caddy_config:
  cache: