{
 "title": "Logs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "Query" }
  ]
 },
 "panels": [
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({container=~\"^(simbuka).*\"}[$__interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Simbuka Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Simbuka",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{container=~\"^(simbuka-simbuka|kopabata-kopabata).*\"} != \"/readiness\" |~ \"(?i)$Query\"",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Simbuka Migrations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Simbuka Migrations",
     "type": "logs",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "{container=~\"^(.*-migrations).*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Proxy Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proxy",
     "type": "logs",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "{container=~\"^(simbuka-proxy).*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Supporting Container Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Supporting Containers",
     "type": "logs",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{container=~\".+\",container!~\"^(monitoring|simbuka-simbuka|kopabata-kopabata|simbuka-proxy|simbuka-database-viewer|simbuka-cache-viewer|simbuka-migrations).*\"} |~ \"(?i)$Query\""
      }
     ]
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Logs",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "{container=~\".+\"} |~ \"(?i)$Query\""
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoring Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Monitoring",
     "type": "logs",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "{container=~\"^monitoring.*\"}"
      }
     ]
    }
   ]
  }
 ]
}