{
 "title": "Postgres",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"postgres-exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{instance=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Shared Buffers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Effective Cache",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max WAL Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_wal_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Seq Page Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_seq_page_cost{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Parallel Workers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_fetched{instance=\"$instance\",datname!~\"template[01]\"}[$__rate_interval])",
     "legendFormat": "{{datname}} SELECT (index scan)"
    },
    {
     "expr": "irate(pg_stat_database_tup_returned{instance=\"$instance\",datname!~\"template[01]\"}[$__rate_interval])",
     "legendFormat": "{{datname}} SELECT (table scan)"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_updated{datname=~\"$datname\",datname!~\"template[01]\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_inserted{datname=~\"$datname\", datname!~\"template[01]\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Total queries count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(pg_stat_statements_calls_total{datname!~\"template[01]\", instance=~\"$instance\", datname=~\"$datname\"}[$__rate_interval])) by (datname) ",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "sum(increase(pg_stat_statements_calls_total{datname!~\"template[01]\", instance=~\"$instance\"}[$__rate_interval])) by (instance) ",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_deleted{datname=~\"$datname\",datname!~\"template[01]\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"$datname\", datname!~\"template[01]\"}[$__rate_interval])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"$datname\", datname!~\"template[01]\"}[$__rate_interval])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"$instance\", mode=~\"$mode\", datname!~\"template[01]|postgres\"}",
     "legendFormat": "{{datname}}, {{mode}}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\", datname=~\"$datname\", datname!~\"template[01]\"}[$__rate_interval])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname=~\"$datname\", datname!~\"template[01]\"}[$__rate_interval])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{instance=\"$instance\"} > 0",
     "legendFormat": "{{datname}} max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    { "expr": "pg_settings_max_connections", "legendFormat": "max_connections" },
    {
     "expr": "sum(pg_stat_activity_count{instance=\"$instance\"})",
     "legendFormat": "total_connections"
    },
    {
     "expr": "sum by (datname) (pg_stat_activity_count{instance=\"$instance\", datname!~\"template[01]\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Connections by database state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum by (datname, state) (pg_stat_activity_count{instance=\"$instance\",state=\"idle\",datname!~\"template[01]\"})",
     "legendFormat": "{{datname}} {{state}}"
    },
    {
     "expr": "sum by (datname, state) (pg_stat_activity_count{instance=\"$instance\",state=\"idle in transaction\",datname!~\"template[01]\"})",
     "legendFormat": "{{datname}} {{state}}"
    },
    {
     "expr": "sum by (datname, state) (pg_stat_activity_count{instance=\"$instance\",state=\"active\",datname!~\"template[01]\"})",
     "legendFormat": "{{datname}} {{state}}"
    },
    {
     "expr": "sum by (datname, state) (pg_stat_activity_count{instance=\"$instance\",state=\"idle in transaction (aborted)\",datname!~\"template[01]\"}) > 0",
     "legendFormat": "{{datname}} {{state}}"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=\"$instance\",state=\"idle\"})",
     "legendFormat": "total idle"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=\"$instance\",state=\"idle in transaction\"})",
     "legendFormat": "total idle in transaction"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=\"$instance\",state=\"active\"})",
     "legendFormat": "total active"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=\"$instance\",state=\"idle in transaction (aborted)\"})",
     "legendFormat": "total idle in transaction (aborted)"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{instance=\"$instance\", datname=~\"$datname\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time_total[$__rate_interval])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time_total[$__rate_interval])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance=\"$instance\", datname!~\"template[01]\"}",
     "legendFormat": "{{datname}}"
    },
    { "expr": "sum(pg_database_size_bytes)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{datname=~\"$datname\", datname!~\"template[01]|postgres\"} / (pg_stat_database_blks_read{datname=~\"$datname\",datname!~\"template[01]|postgres\"} + pg_stat_database_blks_hit{datname=~\"$datname\",datname!~\"template[01]|postgres\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Replication Lag (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_replication_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication Lag (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_replication_pg_wal_lsn_diff{instance=~\"$instance\"}",
     "legendFormat": "{{application_name}}"
    }
   ]
  }
 ]
}