name: Build and scan container
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and scan container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy on source code (filesystem scan)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "library"
          severity: "CRITICAL"
