name: Deploy PR Preview

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          export_environment_variables: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init & Apply
        id: terraform
        run: |
          cd infrastructure/workflow-deploy
          echo "🔧 Starting Terraform init"
          terraform init

          echo "📦 Running terraform plan"
          terraform plan -input=false \
            -var="docker_image_url=justinaspakalnis/application:pr-6" \
            -var="region=europe-west1" \
            -var="database_password=${{ secrets.DATABASE_PASSWORD }}" \
            -var="db_ip=${{ secrets.AUTHORIZED_IP }}" \
            -var="pr_number=${{ github.event.pull_request.number }}"

          echo "🚀 Applying Terraform"
          terraform apply -auto-approve -input=false \
            -var="docker_image_url=justinaspakalnis/application:pr-6" \
            -var="region=europe-west1" \
            -var="database_password=${{ secrets.DATABASE_PASSWORD }}" \
            -var="db_ip=${{ secrets.AUTHORIZED_IP }}" \
            -var="pr_number=${{ github.event.pull_request.number }}"
          echo "preview_url=$(terraform output -raw cloud_run_url)" >> $GITHUB_OUTPUT

      - name: Comment with Preview Link
        # if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ Preview deployed: [Click to view](${{ steps.terraform.outputs.preview_url }})
