name: Deploy PR Preview

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug event payload
        run: echo '${{ toJson(github.event.workflow_run) }}'

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          export_environment_variables: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init & Apply
        run: |
          cd infrastructure/deploy
          terraform init
          terraform apply -auto-approve \
            -var="docker_image_url=${{ vars.DOCKERHUB_USERNAME }}/application:pr-6"
            -var="region=europe-west1"
            -var="project_id=deploy-pr-${{ github.event.pull_request.number }}"
            -var="database_password=testing"
            -var="db_ip=${{ secrets.AUTHORIZED_IP }}"
