name: Deploy PR Preview

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug event payload
        run: echo '${{ github.event.pull_request.number }}'

      - name: Debug event payload sdfs
        run: echo '${{ github.event.pull_request }}'

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          export_environment_variables: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init & Apply
        run: |
          cd infrastructure/workflow-deploy

          echo "🔧 Starting Terraform init"
          terraform init

          echo "📦 Running terraform plan"
          terraform plan -input=false \
            -var="docker_image_url=${{ vars.DOCKERHUB_USERNAME }}/application:pr-6" \
            -var="region=europe-west1" \
            -var="database_password=${{ secrets.DATABASE_PASSWORD }}" \
            -var="db_ip=${{ secrets.AUTHORIZED_IP }}" \
            -var="pr_number=${{ github.event.pull_request.number }}"

          echo "🚀 Applying Terraform"
          terraform apply -auto-approve -input=false \
            -var="docker_image_url=${{ vars.DOCKERHUB_USERNAME }}/application:pr-6" \
            -var="region=europe-west1" \
            -var="database_password=${{ secrets.DATABASE_PASSWORD }}" \
            -var="db_ip=${{ secrets.AUTHORIZED_IP }}" \
            -var="pr_number=${{ github.event.pull_request.number }}"
