name: Build multiplatform image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build multiplatform image
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/application

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          sbom: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
